language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/tester tests -C --coverage coverage.xml --coverage-src src

after_success:
    - bash <(curl -s https://codecov.io/bash)